<?php
/**
 * @category  Trustedshops
 * @package   Trustedshops\Trustedshops
 * @author    Trusted Shops GmbH
 * @copyright 2016 Trusted Shops GmbH
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link      http://www.trustedshops.de/
 */
?>
<?php /** @var \Trustedshops\Trustedshops\Block\Rating $this */ ?>
<?php if ($this->isActive()) : ?>
    <?php if ($this->isExpert()) : ?>
        <?php echo $this->getCode() ?>
    <?php else : ?>
        <script type="text/javascript"
                src="//widgets.trustedshops.com/reviews/tsSticker/tsProductStickerSummary.js"></script>
        <script type="text/javascript">
            var summaryBadge = new productStickerSummary();
            summaryBadge.showSummary(
                {
                    'tsId': '<?php echo $this->getTsId() ?>',
                    'sku': ['<?php echo $this->getProductSku(null) ?>'],
                    'element': '#ts_product_widget',
                    'starColor': '<?php echo $this->getStarColor() ?>',
                    'starSize': '<?php echo $this->getStarSize() ?>',
                    'fontSize': '<?php echo $this->getFontSize() ?>',
                    'showRating': true,
                    'scrollToReviews': false
                }
            );
        </script>
    <?php endif; ?>
<?php endif; ?>
